<a href="https://colab.research.google.com/github/arwahh/Python-_libraries/blob/main/Array_manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import numpy as np

arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape(2, 3)
print(reshaped)


[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
flat = arr.flatten()
print(flat)


[1 2 3 4 5 6]


In [ ]:
arr = np.array([[1,2,3],
                [4,5,6]])
print(arr.T)


[[1 4]
 [2 5]
 [3 6]]


In [ ]:
A = np.array([1,2,3])
B = np.array([4,5,6])

print("Horizontal:", np.hstack([A, B]))
print("Vertical:\n", np.vstack([A, B]))


Horizontal: [1 2 3 4 5 6]
Vertical:
 [[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.array([10,20,30,40])
print(np.split(arr, 2))


[array([10, 20]), array([30, 40])]


In [ ]:
arr = np.array([1,2,3,4])
column = arr[:, np.newaxis]
print(column)


[[1]
 [2]
 [3]
 [4]]


In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(np.dstack((A, B)))


[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [ ]:
arr = np.array([1,2,3])
print(np.repeat(arr, 3))


[1 1 1 2 2 2 3 3 3]


In [ ]:
print(np.tile(np.array([1,2]), 3))


[1 2 1 2 1 2]


In [ ]:
arr = np.array([[1,2],[3,4]])
swapped = arr[[1, 0]]
print(swapped)


[[3 4]
 [1 2]]


In [ ]:
arr = np.array([[10,20,30],[40,50,60]])
new_arr = np.delete(arr, 1, axis=1)
print(new_arr)


[[10 30]
 [40 60]]
