<a href="https://colab.research.google.com/github/arwahh/Python-_libraries/blob/main/file_input_output.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
np.savetxt("data.txt", arr)

print("File saved successfully.")


File saved successfully.


In [ ]:
import numpy as np

arr = np.loadtxt("data.txt")
print(arr)


[10. 20. 30. 40. 50.]


In [ ]:
import numpy as np

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

np.savetxt("matrix.csv", arr, delimiter=",")
print("CSV file saved.")


CSV file saved.


In [ ]:
import numpy as np

data = np.loadtxt("matrix.csv", delimiter=",")
print(data)


[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [ ]:
import numpy as np

arr = np.array([1, 3, 5, 7, 9])

# Save
np.save("myarray.npy", arr)

# Load
loaded_arr = np.load("myarray.npy")

print(loaded_arr)


[1 3 5 7 9]


In [ ]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

np.savez("multiple_arrays.npz", first=a, second=b)


In [ ]:
import numpy as np

arr = np.array([[1.2345, 2.3456],
                [3.4567, 4.5678]])

np.savetxt("formatted.txt", arr, fmt="%.2f")


In [ ]:
import numpy as np

new_data = np.array([100, 200, 300])

with open("data.txt", "ab") as f:      # append in binary mode
    np.savetxt(f, new_data)
