<a href="https://colab.research.google.com/github/arwahh/Python-_libraries/blob/main/Handling_missing_values.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr = np.array([2, 4, np.nan, 8, np.nan, 12])
print(np.isnan(arr))


[False False  True False  True False]


In [ ]:
import numpy as np

arr = np.array([2, 4, np.nan, 8, np.nan, 12])
print(np.sum(np.isnan(arr)))


2


In [ ]:
import numpy as np

arr = np.array([2, 4, np.nan, 8, np.nan, 12])
arr_filled = np.nan_to_num(arr, nan=0)

print(arr_filled)


[ 2.  4.  0.  8.  0. 12.]


In [ ]:
import numpy as np

arr = np.array([2, 4, np.nan, 8, np.nan, 12])
mean_val = np.nanmean(arr)     # mean ignoring NaN

arr2 = np.where(np.isnan(arr), mean_val, arr)

print("Mean =", mean_val)
print(arr2)


Mean = 6.5
[ 2.   4.   6.5  8.   6.5 12. ]


In [ ]:
import numpy as np

arr = np.array([5, np.nan, 9, np.nan, 12])
clean = arr[~np.isnan(arr)]

print(clean)


[ 5.  9. 12.]


In [ ]:
import numpy as np

arr = np.array([[1, 2, np.nan],
                [4, 5, 6],
                [np.nan, 8, 9]])

print(np.isnan(arr).any(axis=1))


[ True False  True]


In [ ]:
import numpy as np

arr = np.array([[1, np.nan, 3],
                [4, 5, np.nan],
                [np.nan, 8, 9]])

row_means = np.nanmean(arr, axis=1)

# Replace NaN using broadcasting
inds = np.where(np.isnan(arr))
arr[inds] = np.take(row_means, inds[0])

print(arr)


[[1.  2.  3. ]
 [4.  5.  4.5]
 [8.5 8.  9. ]]


In [ ]:
import numpy as np

arr = np.array([[1, np.nan, 3],
                [4, 5, np.nan],
                [np.nan, 8, 9]])

col_means = np.nanmean(arr, axis=0)
inds = np.where(np.isnan(arr))
arr[inds] = np.take(col_means, inds[1])

print(arr)


[[1.  6.5 3. ]
 [4.  5.  6. ]
 [2.5 8.  9. ]]
