<a href="https://colab.research.google.com/github/arwahh/Python-_libraries/blob/main/indexing_and_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:


import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[0])   # first
print(arr[2])   # third
print(arr[-1])  # last


10
30
50


In [ ]:
arr = np.array([1,2,3,4,5])
print(arr[::-1])


[5 4 3 2 1]


In [ ]:
arr = np.array([5, 10, 15, 20, 25, 30])
print(arr[1:4])


[10 15 20]


In [ ]:
arr = np.array([2,4,6,8,10,12])
print(arr[::2])


[ 2  6 10]


In [ ]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(arr[1:3, 1:3])


[[5 6]
 [8 9]]


In [ ]:
#Using the same array, print:
#element 6
#element 8
print(arr[1, 2])  # 6
print(arr[2, 1])  # 8


6
8


In [ ]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(arr[1, :])   # row
print(arr[:, 2])   # column


[4 5 6]
[3 6 9]


In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr[-3:])


[40 50 60]


In [ ]:
arr = np.array([10,20,30,40,15,50])
print(arr[arr > 25])


[30 40 50]


In [ ]:
arr = np.array([4,5,6,7,8])
arr[:3] = 0
print(arr)


[0 0 0 7 8]


In [ ]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(arr[[0,1,2], [0,1,2]])


[1 5 9]
