<a href="https://colab.research.google.com/github/arwahh/Python-_libraries/blob/main/Linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print("Addition:\n", A + B)
print("Subtraction:\n", A - B)


Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]


In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[2,0],[1,2]])

print(np.dot(A, B))


[[ 4  4]
 [10  8]]


In [ ]:
arr = np.array([[4,6],[3,8]])
print(np.linalg.det(arr))


14.000000000000004


In [ ]:
A = np.array([[4,7],[2,6]])
print(np.linalg.inv(A))


[[ 0.6 -0.7]
 [-0.2  0.4]]


In [ ]:
A = np.array([[1,2,3],[4,5,6]])
print(np.linalg.matrix_rank(A))


2


In [ ]:
A = np.array([[2,1],[1,2]])
eig_vals, eig_vecs = np.linalg.eig(A)

print(eig_vals)
print(eig_vecs)


[3. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [ ]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.trace(A))


15


In [ ]:
A = np.array([[1,0],[0,1]])
print(np.array_equal(A, np.eye(2)))


True


In [ ]:
A = np.array([[1,2],[2,4]])
print(np.linalg.det(A) == 0)   # True → singular


True


In [ ]:
A = np.array([[1,2],[3,4],[5,6]])
print(A.T @ A)


[[35 44]
 [44 56]]


In [ ]:
A = np.array([[1,2],[2,4]])
vals, vecs = np.linalg.eig(A)
print(vals)   # one eigenvalue will be 0 ⇒ null space exists


[0. 5.]


In [ ]:
A = np.array([[1,4],[2,5],[3,6]])
print(A.T)


[[1 2 3]
 [4 5 6]]
