<a href="https://colab.research.google.com/github/arwahh/Python-_libraries/blob/main/Mathematical_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

A = np.array([1,2,3])
B = np.array([4,5,6])

print(A + B)


[5 7 9]


In [ ]:
arr1 = np.array([2,4,6])
arr2 = np.array([1,2,3])

print(arr1 * arr2)


[ 2  8 18]


In [ ]:
arr1 = np.array([10,20,30])
arr2 = np.array([2,4,5])

print(arr1 / arr2)


[5. 5. 6.]


In [ ]:
arr = np.array([4,9,16,25])
print(np.sqrt(arr))


[2. 3. 4. 5.]


In [ ]:
arr = np.array([2,3,4])
print(arr ** 3)


[ 8 27 64]


In [ ]:
arr = np.array([5,10,15,20])

print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())


50
12.5
20
5


In [ ]:
A = np.array([1,2,3])
B = np.array([4,5,6])

print(np.dot(A, B))


32


In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(np.matmul(A, B))


[[19 22]
 [43 50]]


In [ ]:
arr = np.array([1,2,3,4,5])

print(np.var(arr))   # variance
print(np.std(arr))   # standard deviation


2.0
1.4142135623730951


In [ ]:
arr = np.array([1,2,3,4])
print(np.cumsum(arr))


[ 1  3  6 10]


In [ ]:
arr = np.array([1,2,3,4])
print(np.cumprod(arr))


[ 1  2  6 24]


In [ ]:
arr = np.array([2.3456, 7.8911, 3.4567])
print(np.round(arr, 2))


[2.35 7.89 3.46]
