<a href="https://colab.research.google.com/github/arwahh/Python-_libraries/blob/main/Numpy_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

lst = [3, 6, 9, 12]
arr = np.array(lst)
print(arr)


[ 3  6  9 12]


In [ ]:
import numpy as np

arr = np.arange(2, 22, 2)
print(arr)


[ 2  4  6  8 10 12 14 16 18 20]


In [ ]:
arr = np.array([5, 10, 15, 20, 25])
print(arr[2])


15


In [ ]:
arr = np.array([10,20,30,40,50,60])
print(arr[2:5])


[30 40 50]


In [ ]:
arr = np.array([1,2,3,4,5])
rev = arr[::-1]
print(rev)


[5 4 3 2 1]


In [ ]:
import numpy as np

arr = np.arange(1, 10).reshape(3, 3)
print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr.shape)  # (2, 3)
print(arr.size)   # 6 elements
print(arr.dtype)  # int64 or int32


(2, 3)
6
int64


In [ ]:
import numpy as np

A = np.array([1,2,3])
B = np.array([4,5,6])

print(A + B)


[5 7 9]


In [ ]:
import numpy as np

arr = np.array([[1,2],[3,4]])
print(arr * 5)


[[ 5 10]
 [15 20]]
