<a href="https://colab.research.google.com/github/arwahh/Python-_libraries/blob/main/stacking_and_splitting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# stack them vertically
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.vstack((a, b))
print(result)


[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.hstack((a, b))
print(result)


[1 2 3 4 5 6]


In [ ]:

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.column_stack((a, b))
print(result)


[[1 4]
 [2 5]
 [3 6]]


In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
result = np.dstack((a, b))
print(result)


[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [ ]:
arr = np.array([10,20,30,40,50,60])
parts = np.split(arr, 3)
print(parts)


[array([10, 20]), array([30, 40]), array([50, 60])]


In [ ]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

rows = np.vsplit(arr, 3)
print(rows)


[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [ ]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
cols = np.hsplit(arr, 3)
print(cols)


[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [ ]:
arr = np.array([10,20,30,40,50,60,70])
result = np.split(arr, [2, 5])
print(result)


[array([10, 20]), array([30, 40, 50]), array([60, 70])]


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
result = np.concatenate((a, b))
print(result)


[1 2 3 4 5 6]


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
result = np.vstack((a, b, c))
print(result)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
